---
- name: Backup Nginx Service on Oracle Linux
  hosts: all
  gather_facts: yes
  # backup_path: "/opt/backups" (default: /opt/nginx_backups)
  # backup_content: true/false (default: false - backup website content)
  # nginx_version: "1.20.1" (optional - install specific version)
  # use_nginx_official_repo: true/false (default: false - use official repo)

  tasks:
    - name: Set backup variables
      set_fact:
        backup_timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}"
        backup_folder: "{{ backup_path | default('/opt/nginx_backups') }}/nginx_backup_{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}"
    
    - name: Check if nginx is installed
      shell: rpm -q nginx &> /dev/null && echo "true" || echo "false"
      register: nginx_check
      changed_when: false
      ignore_errors: yes
    
    - name: Set nginx installation status
      set_fact:
        nginx_installed: "{{ nginx_check.stdout | default('false') | bool }}"
    
    # Install nginx if not present
    - block:
      - name: Setup official NGINX repository
        block:
          - name: Detect OS version
            shell: grep -oE '[0-9]+' /etc/oracle-release 2>/dev/null | head -1 || grep -oE '[0-9]+' /etc/redhat-release 2>/dev/null | head -1 || echo "8"
            register: os_version
            changed_when: false
          
          - name: Disable nginx module (Oracle Linux 8+)
            shell: dnf module disable -y nginx 2>/dev/null && dnf module reset -y nginx 2>/dev/null || true
            ignore_errors: yes
          
          - name: Create NGINX repository file
            copy:
              content: |
                [nginx-stable]
                name=nginx stable repo
                baseurl=http://nginx.org/packages/centos/{{ os_version.stdout }}/$basearch/
                gpgcheck=1
                enabled=1
                gpgkey=https://nginx.org/keys/nginx_signing.key
                module_hotfixes=true
              dest: /etc/yum.repos.d/nginx.repo
              mode: '0644'
          
          - name: Import NGINX GPG key
            shell: rpm --import https://nginx.org/keys/nginx_signing.key
            ignore_errors: yes
        when: use_nginx_official_repo | default(false) | bool
      
      - name: Install EPEL repository (for default repo)
        shell: |
          if command -v dnf &> /dev/null; then
              dnf install -y epel-release || true
          else
              yum install -y epel-release || true
          fi
        when: not (use_nginx_official_repo | default(false) | bool)
        ignore_errors: yes
      
      - name: Install nginx
        shell: |
          PKG_MGR=$(command -v dnf || command -v yum)
          {% if nginx_version is defined and nginx_version != '' %}
          $PKG_MGR install -y "nginx-{{ nginx_version }}" || $PKG_MGR install -y nginx
          {% else %}
          $PKG_MGR install -y nginx
          {% endif %}
        register: nginx_install
      
      - name: Verify nginx installation
        shell: rpm -q nginx &> /dev/null && echo "true" || echo "false"
        register: nginx_verify
        changed_when: false
      
      - name: Update nginx status
        set_fact:
          nginx_installed: "{{ nginx_verify.stdout | bool }}"
      
      - name: Fail if installation unsuccessful
        fail:
          msg: "Failed to install nginx"
        when: not (nginx_installed | bool)
      
      when: not (nginx_installed | bool)
    
    # Gather nginx information
    - name: Get nginx information
      shell: |
        nginx -v 2>&1
      register: nginx_version_info
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Get nginx service status
      shell: systemctl is-active nginx 2>/dev/null || echo "inactive"
      register: nginx_status
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Get nginx configuration directory
      shell: |
        if [ -d /etc/nginx ]; then
            echo "/etc/nginx"
        else
            nginx -t 2>&1 | grep "configuration file" | awk '{print $NF}' | xargs dirname || echo "/etc/nginx"
        fi
      register: nginx_config_dir
      changed_when: false
      when: nginx_installed
    
    - name: Get nginx main configuration file
      shell: nginx -t 2>&1 | grep "configuration file" | awk '{print $NF}' | head -1 || echo "/etc/nginx/nginx.conf"
      register: nginx_main_config
      changed_when: false
      when: nginx_installed
    
    # Perform backup
    - name: Create backup directory
      file:
        path: "{{ backup_folder }}"
        state: directory
        mode: '0755'
      when: nginx_installed
    
    - name: Backup nginx main configuration
      copy:
        src: "{{ nginx_main_config.stdout }}"
        dest: "{{ backup_folder }}/nginx.conf"
        remote_src: yes
        mode: '0644'
      when: nginx_installed
    
    - name: Backup nginx configuration directory
      shell: |
        cp -r "{{ nginx_config_dir.stdout }}" "{{ backup_folder }}/etc_nginx"
      when: nginx_installed
    
    - name: Backup nginx systemd service file
      shell: |
        for svc in /usr/lib/systemd/system/nginx.service /etc/systemd/system/nginx.service /lib/systemd/system/nginx.service; do
            [ -f "$svc" ] && cp "$svc" "{{ backup_folder }}/nginx.service" && exit 0
        done
      ignore_errors: yes
      when: nginx_installed
    
    - name: Backup website content (if requested)
      shell: |
        mkdir -p "{{ backup_folder }}/website_content"
        grep -rh "root " "{{ nginx_config_dir.stdout }}"/*.conf "{{ nginx_config_dir.stdout }}"/conf.d/*.conf 2>/dev/null | \
        grep -v "^#" | awk '{print $2}' | sed 's/;//' | sort -u | while read doc_root; do
            [ -d "$doc_root" ] && cp -r "$doc_root" "{{ backup_folder }}/website_content/$(echo $doc_root | tr '/' '_' | sed 's/^_//')" 2>/dev/null
        done
      ignore_errors: yes
      when: 
        - nginx_installed
        - backup_content | default(false) | bool
    
    - name: Create backup summary
      copy:
        content: |
          Nginx Backup Summary
          ===================
          Date: {{ ansible_date_time.date }}
          Time: {{ ansible_date_time.time }}
          Host: {{ inventory_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Backup Location: {{ backup_folder }}
          
          Nginx Information:
          - Version: {{ nginx_version_info.stdout | default('Unknown') }}
          - Service Status: {{ nginx_status.stdout | default('Unknown') }}
          - Config Directory: {{ nginx_config_dir.stdout | default('Unknown') }}
          - Main Config: {{ nginx_main_config.stdout | default('Unknown') }}
          
          Files Backed Up:
          - nginx.conf (main configuration)
          - etc_nginx/ (configuration directory)
          - nginx.service (systemd service)
          {% if backup_content | default(false) %}
          - website_content/ (website files)
          {% endif %}
        dest: "{{ backup_folder }}/backup_summary.txt"
        mode: '0644'
      when: nginx_installed
    
    - name: Stop nginx service after backup
      systemd:
        name: nginx
        state: stopped
      when: nginx_installed
      ignore_errors: yes
      register: nginx_stopped
    
    - name: Display backup completion
      debug:
        msg:
          - "=========================================="
          - "Nginx Backup Completed"
          - "Location: {{ backup_folder }}"
          - "Version: {{ nginx_version_info.stdout | default('Unknown') }}"
          - "Service Stopped: {{ 'Yes' if nginx_stopped is succeeded else 'Failed' }}"
          - "=========================================="
      when: nginx_installed
