---
- name: Delete Hyper-V VM Snapshots
  hosts: all
  gather_facts: no
  vars:
    vm_name: "test"  # Required: VM name
    snapshot_name: "AWX_Snapshot_2025-11-05_16-13-33"  # Required: Snapshot name to delete
    delete_all_snapshots: false  # If true, deletes all snapshots for the VM
    
  tasks:
    - name: Validate required variables
      fail:
        msg: "vm_name is required. Set snapshot_name for specific snapshot or delete_all_snapshots=true for all."
      when: vm_name == "" or (snapshot_name == "" and not delete_all_snapshots)
      
    - name: Delete specific snapshot
      win_shell: |
        try {
          $ProgressPreference = 'SilentlyContinue'
          $vmName = "{{ vm_name | replace('"', '`"') }}"
          $snapshotName = "{{ snapshot_name | replace('"', '`"') }}"
          Remove-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false -ErrorAction Stop *> $null
          Write-Host "SUCCESS"
          exit 0
        } catch {
          Write-Host "FAILED: $($_.Exception.Message)"
          exit 1
        }
      register: delete_result
      when: snapshot_name != "" and not delete_all_snapshots
      failed_when: false
      
    - name: Delete all snapshots for VM
      win_shell: |
        try {
          $ProgressPreference = 'SilentlyContinue'
          $vmName = "{{ vm_name | replace('"', '`"') }}"
          $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction Stop)
          if ($snapshots.Count -gt 0) {
              $count = $snapshots.Count
              $snapshots | Remove-VMSnapshot -Confirm:$false -ErrorAction Stop *> $null
              Write-Host "SUCCESS: Deleted $count snapshot(s)"
          } else {
              Write-Host "No snapshots found"
          }
          exit 0
        } catch {
          Write-Host "FAILED: $($_.Exception.Message)"
          exit 1
        }
      register: delete_all_result
      when: delete_all_snapshots
      failed_when: false
      
    - name: Display result for specific snapshot
      debug:
        msg: "{{ delete_result.stdout_lines }}"
      when: delete_result is defined and delete_result is not skipped
      
    - name: Display result for all snapshots
      debug:
        msg: "{{ delete_all_result.stdout_lines }}"
      when: delete_all_result is defined and delete_all_result is not skipped
      
    - name: Check if delete succeeded
      fail:
        msg: "Delete operation failed"
      when: >
        (delete_result is defined and delete_result is not skipped and delete_result.rc != 0) or
        (delete_all_result is defined and delete_all_result is not skipped and delete_all_result.rc != 0)

