---
- name: Delete Hyper-V VM Snapshots
  hosts: all
  gather_facts: no
  vars:
    vm_name: "test"  # Required: VM name
    snapshot_name: "AWX_Snapshot_2025-11-05_16-13-33"  # Required: Snapshot name to delete
    delete_all_snapshots: false  # If true, deletes all snapshots for the VM
    
  tasks:
    - name: Validate required variables
      fail:
        msg: "vm_name is required. Set snapshot_name for specific snapshot or delete_all_snapshots=true for all."
      when: vm_name == "" or (snapshot_name == "" and not delete_all_snapshots)
      
    - name: Delete specific snapshot
      win_shell: |
        $ErrorActionPreference = 'Continue'
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $ProgressPreference = 'SilentlyContinue'
        
        $vmName = '{{ vm_name }}'
        $snapshotName = '{{ snapshot_name }}'
        
        try {
            $result = Remove-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false -ErrorAction Stop 2>&1
            [Console]::WriteLine("SUCCESS: Snapshot '$snapshotName' deleted from VM '$vmName'")
            exit 0
        } catch {
            [Console]::WriteLine("ERROR: Failed to delete snapshot - $($_.Exception.Message)")
            exit 1
        }
      register: delete_result
      when: snapshot_name != "" and not delete_all_snapshots
      args:
        executable: powershell.exe
      changed_when: delete_result.rc == 0
      failed_when: delete_result.rc != 0
      ignore_errors: yes
      
    - name: Delete all snapshots for VM
      win_shell: |
        $ErrorActionPreference = 'Continue'
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $ProgressPreference = 'SilentlyContinue'
        
        $vmName = '{{ vm_name }}'
        
        try {
            $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction Stop)
            if ($snapshots.Count -gt 0) {
                $count = $snapshots.Count
                $snapshots | Remove-VMSnapshot -Confirm:$false -ErrorAction Stop
                [Console]::WriteLine("SUCCESS: Deleted $count snapshot(s) from VM '$vmName'")
            } else {
                [Console]::WriteLine("INFO: No snapshots found for VM '$vmName'")
            }
            exit 0
        } catch {
            [Console]::WriteLine("ERROR: Failed to delete snapshots - $($_.Exception.Message)")
            exit 1
        }
      register: delete_all_result
      when: delete_all_snapshots
      args:
        executable: powershell.exe
      changed_when: delete_all_result.rc == 0
      failed_when: delete_all_result.rc != 0
      ignore_errors: yes
      
    - name: Display result for specific snapshot
      debug:
        msg: "{{ delete_result.stdout_lines | default(['No output received']) }}"
      when: delete_result is defined and delete_result is not skipped
      
    - name: Display result for all snapshots
      debug:
        msg: "{{ delete_all_result.stdout_lines | default(['No output received']) }}"
      when: delete_all_result is defined and delete_all_result is not skipped

