---
- name: Delete Last Hyper-V VM Snapshots
  hosts: all
  gather_facts: no
  # vm_names can be set in AWX as an extra variable or survey
  # Examples:
  #   - String from survey: vm_names: "vm1,vm2" or vm_names: "vm1"
  #   - List: vm_names: ["vm1", "vm2"]
  #   - Empty/not set: vm_names: "" or leave unset (will delete last snapshot for all VMs)
    
  tasks:
    - name: Set default vm_names if not defined
      set_fact:
        vm_names: ""
      when: vm_names is not defined
    
    - name: Normalize vm_names to a list (handle string from AWX survey)
      set_fact:
        vm_names_normalized: "{{ vm_names.split(',') | map('trim') | select | list }}"
      when: vm_names is defined and vm_names is string and vm_names != '' and ',' in vm_names
      
    - name: Normalize vm_names to a list (single VM)
      set_fact:
        vm_names_normalized: "{{ [vm_names | trim] }}"
      when: vm_names is defined and vm_names is string and vm_names != '' and ',' not in vm_names
      
    - name: Normalize vm_names to a list (already a list)
      set_fact:
        vm_names_normalized: "{{ vm_names | list }}"
      when: vm_names is defined and vm_names is iterable and vm_names is not string
      
    - name: Set empty list if vm_names is empty
      set_fact:
        vm_names_normalized: []
      when: vm_names is not defined or vm_names == '' or vm_names == None
      
    - name: Get all VMs if no specific VMs specified
      win_shell: |
        $ErrorActionPreference = 'Stop'
        try {
            $vms = @(Get-VM | Select-Object -ExpandProperty Name)
            if ($vms.Count -eq 0) {
                Write-Output '[]'
            } elseif ($vms.Count -eq 1) {
                Write-Output "[`"$($vms[0])`"]"
            } else {
                $vms | ConvertTo-Json -Compress
            }
        } catch {
            Write-Output '[]'
        }
      register: all_vms
      when: vm_names_normalized | length == 0
      changed_when: false
      
    - name: Set VM list from all VMs
      set_fact:
        target_vms: "{{ all_vms.stdout | default('[]') | trim | from_json }}"
      when: vm_names_normalized | length == 0
      
    - name: Set VM list from provided names
      set_fact:
        target_vms: "{{ vm_names_normalized }}"
      when: vm_names_normalized | length > 0
      
    - name: Display VMs to delete last snapshot from
      debug:
        msg: "Deleting last snapshot for VMs: {{ target_vms }}"
        
    - name: List all snapshots for target VMs
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $ErrorActionPreference = 'Stop'
        $vmName = "{{ item | replace('"', '`"') }}"
        
        try {
            # Get VM
            $vm = Get-VM -Name $vmName -ErrorAction Stop
            
            # Get all snapshots for this VM, sorted by creation time (oldest first for display)
            $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue | 
                          Sort-Object CreationTime)
            
            if ($snapshots.Count -eq 0) {
                Write-Output "VM: $vmName - No snapshots found"
            } else {
                Write-Output "VM: $vmName - Total snapshots: $($snapshots.Count)"
                foreach ($snapshot in $snapshots) {
                    $creationTime = $snapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss')
                    Write-Output "  - $($snapshot.Name) (Created: $creationTime)"
                }
            }
        }
        catch {
            Write-Output "VM: $vmName - ERROR: $($_.Exception.Message)"
        }
      loop: "{{ target_vms }}"
      register: list_snapshots_results
      changed_when: false
      failed_when: false
      
    - name: Display all snapshots
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ list_snapshots_results.results }}"
      loop_control:
        label: "{{ item.item }}"
        
    - name: Identify last (most recent) snapshot for each VM
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $ErrorActionPreference = 'Stop'
        $vmName = "{{ item | replace('"', '`"') }}"
        
        try {
            # Get all snapshots for this VM, sorted by creation time (most recent first)
            $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue | 
                          Sort-Object CreationTime -Descending)
            
            if ($snapshots.Count -eq 0) {
                Write-Output "VM: $vmName - No snapshots to delete"
            } else {
                $lastSnapshot = $snapshots[0]
                $creationTime = $lastSnapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss')
                Write-Output "VM: $vmName - Last snapshot to be deleted: '$($lastSnapshot.Name)' (Created: $creationTime)"
            }
        }
        catch {
            Write-Output "VM: $vmName - ERROR: $($_.Exception.Message)"
        }
      loop: "{{ target_vms }}"
      register: last_snapshot_info
      changed_when: false
      failed_when: false
      
    - name: Display last snapshots that will be deleted
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ last_snapshot_info.results }}"
      loop_control:
        label: "{{ item.item }}"
        
    - name: Get and delete last snapshot for each VM
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $ErrorActionPreference = 'Stop'
        $vmName = "{{ item | replace('"', '`"') }}"
        
        try {
            # Get VM
            $vm = Get-VM -Name $vmName -ErrorAction Stop
            
            # Get all snapshots for this VM, sorted by creation time (most recent first)
            $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue | 
                          Sort-Object CreationTime -Descending)
            
            if ($snapshots.Count -eq 0) {
                Write-Output "NO_SNAPSHOTS: No snapshots found for VM '$vmName'"
                exit 0
            }
            
            # Get the last (most recent) snapshot
            $lastSnapshot = $snapshots[0]
            $snapshotName = $lastSnapshot.Name
            $creationTime = $lastSnapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss')
            
            # Delete the last snapshot
            Remove-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false -ErrorAction Stop
            
            Write-Output "SUCCESS: Deleted last snapshot '$snapshotName' (created: $creationTime) for VM '$vmName'"
        }
        catch {
            Write-Output "ERROR: Failed to delete snapshot for VM '$vmName': $($_.Exception.Message)"
            exit 1
        }
      loop: "{{ target_vms }}"
      register: delete_results
      failed_when: delete_results.rc != 0 and 'NO_SNAPSHOTS' not in delete_results.stdout
      changed_when: delete_results.stdout is search("SUCCESS")
      
    - name: Display deletion summary
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ delete_results.results }}"
      loop_control:
        label: "{{ item.item }}"

