---
- name: Delete Last Hyper-V VM Snapshots
  hosts: all
  gather_facts: no
  # vm_names can be set in AWX as an extra variable or survey
  # Examples:
  #   - String from survey: vm_names: "vm1,vm2" or vm_names: "vm1"
  #   - List: vm_names: ["vm1", "vm2"]
  #   - Empty/not set: vm_names: "" or leave unset (will delete last snapshot for all VMs)
    
  tasks:
    - name: Normalize vm_names to a list (handle string from AWX survey)
      set_fact:
        vm_names_normalized: >-
          {%- if vm_names is not defined or vm_names == '' -%}
            []
          {%- elif vm_names is string -%}
            {%- if ',' in vm_names -%}
              {{ vm_names.split(',') | map('trim') | list | select('length') | list }}
            {%- else -%}
              {{ [vm_names | trim] }}
            {%- endif -%}
          {%- elif vm_names is iterable and vm_names is not string -%}
            {{ vm_names | list }}
          {%- else -%}
            []
          {%- endif -%}
      
    - name: Get all VMs if no specific VMs specified
      win_shell: |
        $ErrorActionPreference = 'Stop'
        try {
            $vms = @(Get-VM | Select-Object -ExpandProperty Name)
            if ($vms.Count -eq 0) {
                Write-Output '[]'
            } elseif ($vms.Count -eq 1) {
                Write-Output "[`"$($vms[0])`"]"
            } else {
                $vms | ConvertTo-Json -Compress
            }
        } catch {
            Write-Output '[]'
        }
      register: all_vms
      when: vm_names_normalized | length == 0
      changed_when: false
      
    - name: Set VM list from all VMs
      set_fact:
        target_vms: "{{ all_vms.stdout | default('[]') | trim | from_json }}"
      when: vm_names_normalized | length == 0
      
    - name: Set VM list from provided names
      set_fact:
        target_vms: "{{ vm_names_normalized }}"
      when: vm_names_normalized | length > 0
      
    - name: Display VMs to delete last snapshot from
      debug:
        msg: "Deleting last snapshot for VMs: {{ target_vms }}"
        
    - name: Get and delete last snapshot for each VM
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $ErrorActionPreference = 'Stop'
        $vmName = "{{ item | replace('"', '`"') }}"
        
        try {
            # Get VM
            $vm = Get-VM -Name $vmName -ErrorAction Stop
            
            # Get all snapshots for this VM, sorted by creation time (most recent first)
            $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue | 
                          Sort-Object CreationTime -Descending)
            
            if ($snapshots.Count -eq 0) {
                Write-Output "NO_SNAPSHOTS: No snapshots found for VM '$vmName'"
                exit 0
            }
            
            # Get the last (most recent) snapshot
            $lastSnapshot = $snapshots[0]
            $snapshotName = $lastSnapshot.Name
            $creationTime = $lastSnapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss')
            
            # Delete the last snapshot
            Remove-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false -ErrorAction Stop
            
            Write-Output "SUCCESS: Deleted last snapshot '$snapshotName' (created: $creationTime) for VM '$vmName'"
        }
        catch {
            Write-Output "ERROR: Failed to delete snapshot for VM '$vmName': $($_.Exception.Message)"
            exit 1
        }
      loop: "{{ target_vms }}"
      register: delete_results
      failed_when: delete_results.rc != 0 and 'NO_SNAPSHOTS' not in delete_results.stdout
      changed_when: delete_results.stdout is search("SUCCESS")
      
    - name: Display deletion summary
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ delete_results.results }}"
      loop_control:
        label: "{{ item.item }}"

