---
- name: List Hyper-V VM Snapshots
  hosts: hyperv_hosts
  gather_facts: no
  vars:
    vm_name: ""  # Specific VM name, empty means all VMs
    
  tasks:
    - name: List all snapshots for all VMs
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $output = @()
        Get-VM -ErrorAction SilentlyContinue | ForEach-Object {
            $vmName = $_.Name
            $snapshots = Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue
            foreach ($snapshot in $snapshots) {
                $output += "$vmName | $($snapshot.Name) | $($snapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss'))"
            }
        }
        if ($output.Count -eq 0) {
            "No snapshots found"
        } else {
            "VM | Snapshot Name | Creation Time"
            "-----------------------------------------------------------"
            $output
        }
      register: all_snapshots
      when: vm_name == ""
      changed_when: false
      
    - name: List snapshots for specific VM
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $vmName = "{{ vm_name | replace('"', '`"') }}"
        $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction Stop)
        if ($snapshots.Count -eq 0) {
            "No snapshots found for VM: $vmName"
        } else {
            "VM | Snapshot Name | Creation Time"
            "-----------------------------------------------------------"
            foreach ($snapshot in $snapshots) {
                "$vmName | $($snapshot.Name) | $($snapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss'))"
            }
        }
      register: vm_snapshots
      when: vm_name != ""
      changed_when: false
      
    - name: Display all snapshots
      debug:
        msg: "{{ all_snapshots.stdout_lines }}"
      when: vm_name == ""
      
    - name: Display VM snapshots
      debug:
        msg: "{{ vm_snapshots.stdout_lines }}"
      when: vm_name != ""

