---
- name: List Hyper-V VM Snapshots
  hosts: hyperv_hosts
  gather_facts: no
  vars:
    vm_name: ""  # Specific VM name, empty means all VMs
    
  tasks:
    - name: List all snapshots for all VMs
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        try {
            $output = @()
            Get-VM -ErrorAction SilentlyContinue | ForEach-Object {
                $vmName = $_.Name
                $snapshots = Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue
                foreach ($snapshot in $snapshots) {
                    $line = "$vmName | $($snapshot.Name) | $($snapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss')) | $($snapshot.ParentSnapshotName)"
                    $output += $line
                }
            }
            if ($output.Count -eq 0) {
                Write-Output "No snapshots found"
            } else {
                Write-Output "VM | Snapshot Name | Creation Time | Parent Snapshot"
                Write-Output "-----------------------------------------------------------"
                $output | ForEach-Object { Write-Output $_ }
            }
        } catch {
            Write-Output "ERROR: $($_.Exception.Message)"
            throw
        }
      register: all_snapshots
      when: vm_name == ""
      changed_when: false
      
    - name: List snapshots for specific VM
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $vmName = @"
        {{ vm_name }}
        "@.Trim()
        try {
            $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction Stop)
            if ($snapshots.Count -eq 0) {
                Write-Output "No snapshots found for VM: $vmName"
            } else {
                Write-Output "VM | Snapshot Name | Creation Time | Parent Snapshot"
                Write-Output "-----------------------------------------------------------"
                foreach ($snapshot in $snapshots) {
                    $line = "$vmName | $($snapshot.Name) | $($snapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss')) | $($snapshot.ParentSnapshotName)"
                    Write-Output $line
                }
            }
        } catch {
            Write-Output "ERROR: $($_.Exception.Message)"
            throw
        }
      register: vm_snapshots
      when: vm_name != ""
      changed_when: false
      
    - name: Display all snapshots
      debug:
        msg: "{{ all_snapshots.stdout_lines }}"
      when: vm_name == ""
      
    - name: Display VM snapshots
      debug:
        msg: "{{ vm_snapshots.stdout_lines }}"
      when: vm_name != ""

