---
- name: List Hyper-V VM Snapshots
  hosts: hyperv_hosts
  gather_facts: no
  vars:
    vm_name: ""  # Specific VM name, empty means all VMs
    
  tasks:
    - name: List all snapshots for all VMs
      win_shell: |
        try {
          $ProgressPreference = 'SilentlyContinue'
          $output = @()
          Get-VM -ErrorAction SilentlyContinue | ForEach-Object {
              $vmName = $_.Name
              $snapshots = Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue
              foreach ($snapshot in $snapshots) {
                  $output += "$vmName | $($snapshot.Name) | $($snapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss'))"
              }
          }
          if ($output.Count -eq 0) {
              Write-Host "No snapshots found"
          } else {
              Write-Host "VM | Snapshot Name | Creation Time"
              Write-Host "-----------------------------------------------------------"
              $output | ForEach-Object { Write-Host $_ }
          }
          exit 0
        } catch {
          Write-Host "FAILED: $($_.Exception.Message)"
          exit 1
        }
      register: all_snapshots
      when: vm_name == ""
      changed_when: false
      failed_when: false
      
    - name: List snapshots for specific VM
      win_shell: |
        try {
          $ProgressPreference = 'SilentlyContinue'
          $vmName = "{{ vm_name | replace('"', '`"') }}"
          $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction Stop)
          if ($snapshots.Count -eq 0) {
              Write-Host "No snapshots found for VM: $vmName"
          } else {
              Write-Host "VM | Snapshot Name | Creation Time"
              Write-Host "-----------------------------------------------------------"
              foreach ($snapshot in $snapshots) {
                  Write-Host "$vmName | $($snapshot.Name) | $($snapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss'))"
              }
          }
          exit 0
        } catch {
          Write-Host "FAILED: $($_.Exception.Message)"
          exit 1
        }
      register: vm_snapshots
      when: vm_name != ""
      changed_when: false
      failed_when: false
      
    - name: Display all snapshots
      debug:
        msg: "{{ all_snapshots.stdout_lines }}"
      when: vm_name == ""
      
    - name: Display VM snapshots
      debug:
        msg: "{{ vm_snapshots.stdout_lines }}"
      when: vm_name != ""

