---
- name: Manage Nginx Service on Oracle Linux
  hosts: all
  gather_facts: yes
  # service_action: "start", "stop", "restart", "status" (required)
  # Example:
  #   - service_action: "start"
  #   - service_action: "stop"
  #   - service_action: "restart"
  #   - service_action: "status"
  tags:
    - start-service
    - stop-service

  tasks:
    - name: Validate service_action parameter
      fail:
        msg: "service_action must be set to 'start', 'stop', 'restart', or 'status'"
      when: service_action is not defined or service_action not in ['start', 'stop', 'restart', 'status']
    
    - name: Check if nginx is installed
      shell: rpm -q nginx &> /dev/null && echo "true" || echo "false"
      register: nginx_check
      changed_when: false
      ignore_errors: yes
    
    - name: Set nginx installation status
      set_fact:
        nginx_installed: "{{ nginx_check.stdout | default('false') | bool }}"
    
    - name: Fail if nginx is not installed
      fail:
        msg: "Nginx is not installed on this host"
      when: not nginx_installed
    
    - name: Get nginx service status before action
      shell: systemctl is-active nginx 2>/dev/null || echo "inactive"
      register: nginx_status_before
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Start nginx service
      systemd:
        name: nginx
        state: started
      when: 
        - nginx_installed
        - service_action == "start"
      register: nginx_start_result
      ignore_errors: yes
    
    - name: Stop nginx service
      systemd:
        name: nginx
        state: stopped
      when: 
        - nginx_installed
        - service_action == "stop"
      register: nginx_stop_result
      ignore_errors: yes
    
    - name: Restart nginx service
      systemd:
        name: nginx
        state: restarted
      when: 
        - nginx_installed
        - service_action == "restart"
      register: nginx_restart_result
      ignore_errors: yes
    
    - name: Get nginx service status after action
      shell: systemctl is-active nginx 2>/dev/null || echo "inactive"
      register: nginx_status_after
      ignore_errors: yes
      changed_when: false
      when: 
        - nginx_installed
        - service_action != "status"
    
    - name: Get detailed nginx service status
      shell: systemctl status nginx --no-pager -l
      register: nginx_detailed_status
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Display service management result
      debug:
        msg:
          - "=========================================="
          - "Nginx Service Management"
          - "Host: {{ inventory_hostname }}"
          - "Action: {{ service_action | upper }}"
          - "Status Before: {{ nginx_status_before.stdout | default('Unknown') }}"
          - "Status After: {{ nginx_status_after.stdout | default(nginx_status_before.stdout) }}"
          - "Result: {{ 'Success' if (nginx_start_result is succeeded or nginx_stop_result is succeeded or nginx_restart_result is succeeded or service_action == 'status') else 'Failed' }}"
          - "=========================================="
      when: nginx_installed
    
    - name: Display detailed status (status action only)
      debug:
        msg: "{{ nginx_detailed_status.stdout_lines }}"
      when: 
        - nginx_installed
        - service_action == "status"

