---
- name: Patch/Update OpenSSH Service on Linux
  hosts: all
  gather_facts: yes
  vars:
    restart_service: true  # Whether to restart SSH service after update
    verify_service: true  # Whether to verify service is running after update
    
  tasks:
    - name: Check if OpenSSH is installed
      command: which sshd
      register: sshd_check
      changed_when: false
      failed_when: false
      
    - name: Fail if OpenSSH is not installed
      fail:
        msg: "OpenSSH is not installed on this system"
      when: sshd_check.rc != 0
      
    - name: Get current OpenSSH version (before update)
      command: sshd -V
      register: openssh_version_before
      changed_when: false
      failed_when: false
      
    - name: Display current OpenSSH version
      debug:
        msg: "Current OpenSSH version: {{ openssh_version_before.stderr | default(openssh_version_before.stdout) | default('unknown') }}"
      
    - name: Get SSH package name based on OS
      set_fact:
        openssh_package: "{{ 'openssh-server' if ansible_pkg_mgr == 'apt' else 'openssh-server' if ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf' else 'openssh' }}"
      
    - name: Update OpenSSH package (Debian/Ubuntu)
      apt:
        name: openssh-server
        state: latest
        update_cache: yes
      become: yes
      register: apt_update_result
      when: ansible_pkg_mgr == 'apt'
      
    - name: Update OpenSSH package (RHEL/CentOS/Fedora)
      yum:
        name: openssh-server
        state: latest
        update_cache: yes
      become: yes
      register: yum_update_result
      when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
      
    - name: Update OpenSSH package (SUSE)
      zypper:
        name: openssh
        state: latest
        update_cache: yes
      become: yes
      register: zypper_update_result
      when: ansible_pkg_mgr == 'zypper'
      
    - name: Update OpenSSH package (Arch Linux)
      pacman:
        name: openssh
        state: latest
        update_cache: yes
      become: yes
      register: pacman_update_result
      when: ansible_pkg_mgr == 'pacman'
      
    - name: Fail if package manager is not supported
      fail:
        msg: "Unsupported package manager: {{ ansible_pkg_mgr }}. Supported: apt, yum, dnf, zypper, pacman"
      when: >
        ansible_pkg_mgr != 'apt' and
        ansible_pkg_mgr != 'yum' and
        ansible_pkg_mgr != 'dnf' and
        ansible_pkg_mgr != 'zypper' and
        ansible_pkg_mgr != 'pacman'
      
    - name: Check if update was performed
      set_fact:
        update_performed: >
          {{ (apt_update_result is defined and apt_update_result.changed) or
             (yum_update_result is defined and yum_update_result.changed) or
             (zypper_update_result is defined and zypper_update_result.changed) or
             (pacman_update_result is defined and pacman_update_result.changed) }}
      
    - name: Get new OpenSSH version (after update)
      command: sshd -V
      register: openssh_version_after
      changed_when: false
      failed_when: false
      
    - name: Display new OpenSSH version
      debug:
        msg: "New OpenSSH version: {{ openssh_version_after.stderr | default(openssh_version_after.stdout) | default('unknown') }}"
      
    - name: Restart SSH service
      systemd:
        name: sshd
        state: restarted
        enabled: yes
      become: yes
      when: restart_service
      register: service_restart
      
    - name: Wait for SSH service to be ready
      wait_for:
        port: 22
        delay: 2
        timeout: 30
      when: restart_service
      delegate_to: localhost
      
    - name: Verify SSH service is running
      systemd:
        name: sshd
      register: sshd_status
      changed_when: false
      when: verify_service
      
    - name: Display service status
      debug:
        msg: |
          SSH Service Status:
          - Active: {{ sshd_status.status.ActiveState | default('unknown') }}
          - Enabled: {{ sshd_status.status.Enabled | default('unknown') }}
          - Main PID: {{ sshd_status.status.MainPID | default('unknown') }}
      when: verify_service and sshd_status.status is defined
      
    - name: Fail if service is not running
      fail:
        msg: "SSH service is not running after update"
      when: >
        verify_service and
        sshd_status.status is defined and
        sshd_status.status.ActiveState != 'active'
      
    - name: Display update summary
      debug:
        msg: |
          OpenSSH update completed!
          Update performed: {{ 'Yes' if update_performed else 'No (already latest version)' }}
          Service restarted: {{ 'Yes' if restart_service and service_restart is defined else 'No' }}
          Service status: {{ sshd_status.status.ActiveState | default('unknown') if verify_service else 'not checked' }}

