---
- name: Patch Nginx on Oracle Linux
  hosts: all
  gather_facts: yes
  # install_updates can be set in AWX as an extra variable
  #   - true: Install available nginx updates (default: false - only check)
  #   - false: Only check for available updates without installing
  #
  # nginx_version_target can be set in AWX as an extra variable
  #   - If specified: Upgrade to specific version (e.g., "1.20.1", "1.18.0-2.el7")
  #   - If not set: Upgrade to latest available in repository (not necessarily latest)
  #   - When switching mainlines (e.g., 1.14 to 1.20), the playbook will automatically
  #     detect and switch the module stream on Oracle Linux 8+
  #   - Examples:
  #     - nginx_version_target: "1.20.1"  (switches to 1.20 stream if needed)
  #     - nginx_version_target: "1.18.0-2.el7"
  #     - nginx_version_target: "1.20"  (upgrades to latest in 1.20 stream)
  #
  # use_nginx_official_repo can be set in AWX as an extra variable
  #   - true: Use official NGINX repository (gets latest stable versions like 1.26.x)
  #   - false: Use default Oracle Linux repository (default: false)
  #   - When enabled, will remove old nginx and set up official repo
  #   - Examples:
  #     - use_nginx_official_repo: true
  #     - use_nginx_official_repo: false

  tasks:
    - name: Get formatted date and time
      set_fact:
        patch_date: "{{ ansible_date_time.date.split('-') | reverse | join('/') }}"
        patch_time: "{{ ansible_date_time.time }}"
    
    - name: Check if nginx is installed
      shell: rpm -q nginx
      register: nginx_check
      ignore_errors: yes
      changed_when: false
    
    - name: Set nginx installation status
      set_fact:
        nginx_installed: "{{ nginx_check.rc == 0 }}"
    
    - name: Fail if nginx is not installed
      fail:
        msg: "Nginx is not installed on this host. Please install nginx before running patch."
      when: not nginx_installed
    
    - name: Get nginx version before patching
      shell: |
        nginx -v 2>&1 | head -1
      register: nginx_version_before
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Get nginx service status before patching
      shell: systemctl is-active nginx 2>/dev/null || echo "inactive"
      register: nginx_service_status_before
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Check if using official NGINX repository
      set_fact:
        use_official_repo: "{{ use_nginx_official_repo | default(false) | bool }}"
      when: nginx_installed
    
    - name: Disable and reset nginx module stream (Oracle Linux 8+)
      shell: |
        if command -v dnf &> /dev/null; then
            dnf module disable -y nginx 2>/dev/null || true
            dnf module reset -y nginx 2>/dev/null || true
        fi
      register: disable_nginx_module
      when: 
        - nginx_installed
        - use_official_repo
      ignore_errors: yes
    
    - name: Remove old nginx package if switching to official repo
      shell: |
        if command -v dnf &> /dev/null; then
            dnf remove -y nginx || true
        elif command -v yum &> /dev/null; then
            yum remove -y nginx || true
        fi
      register: remove_old_nginx
      when: 
        - nginx_installed
        - use_official_repo
      ignore_errors: yes
    
    - name: Remove existing broken nginx repository files
      shell: |
        rm -f /etc/yum.repos.d/nginx*.repo 2>/dev/null || true
      register: remove_old_repo
      when: 
        - nginx_installed
        - use_official_repo
      ignore_errors: yes
    
    - name: Detect OS release version (major version only)
      shell: |
        if [ -f /etc/oracle-release ]; then
            # Extract ONLY major version (8.10 -> 8, 9.3 -> 9)
            cat /etc/oracle-release | grep -oE '[0-9]+' | head -1
        elif [ -f /etc/redhat-release ]; then
            # Extract ONLY major version
            cat /etc/redhat-release | grep -oE '[0-9]+' | head -1
        elif [ -f /etc/os-release ]; then
            # Extract ONLY major version
            grep VERSION_ID /etc/os-release | cut -d'"' -f2 | cut -d'.' -f1
        else
            echo "8"
        fi
      register: os_release_version
      ignore_errors: yes
      changed_when: false
      when: 
        - nginx_installed
        - use_official_repo
    
    - name: Detect system architecture
      shell: |
        uname -m
      register: system_arch
      ignore_errors: yes
      changed_when: false
      when: 
        - nginx_installed
        - use_official_repo
    
    - name: Create official NGINX repository file
      copy:
        content: |
          [nginx-stable]
          name=nginx stable repo
          baseurl=http://nginx.org/packages/centos/{{ os_release_version.stdout | default('8') }}/$basearch/
          gpgcheck=1
          enabled=1
          gpgkey=https://nginx.org/keys/nginx_signing.key
          module_hotfixes=true
        dest: /etc/yum.repos.d/nginx.repo
        mode: '0644'
      register: nginx_repo_created
      when: 
        - nginx_installed
        - use_official_repo
      ignore_errors: yes
    
    - name: Import NGINX GPG key
      shell: |
        rpm --import https://nginx.org/keys/nginx_signing.key || true
      register: nginx_gpg_import
      ignore_errors: yes
      when: 
        - nginx_installed
        - use_official_repo
    
    - name: Update package cache after adding NGINX repo
      shell: |
        if command -v dnf &> /dev/null; then
            dnf makecache || true
        elif command -v yum &> /dev/null; then
            yum makecache || true
        fi
      register: update_cache_after_repo
      ignore_errors: yes
      when: 
        - nginx_installed
        - use_official_repo
    
    - name: Install nginx from official repository
      shell: |
        if command -v dnf &> /dev/null; then
            dnf install -y nginx
        elif command -v yum &> /dev/null; then
            yum install -y nginx
        else
            echo "ERROR: No package manager found (dnf/yum)"
            exit 1
        fi
      register: nginx_install_from_official
      when: 
        - nginx_installed
        - use_official_repo
        - remove_old_nginx is defined
      ignore_errors: yes
    
    - name: Verify nginx installation from official repo
      shell: |
        if rpm -q nginx &> /dev/null; then
            echo "INSTALLED:Yes"
            nginx -v 2>&1 | head -1
            rpm -qi nginx | grep -E "^Version|^Release|^Name" | head -3
        else
            echo "INSTALLED:No"
        fi
      register: nginx_verify_official
      ignore_errors: yes
      changed_when: false
      when: 
        - nginx_installed
        - use_official_repo
        - nginx_install_from_official is defined
    
    - name: Update package cache
      shell: |
        if command -v dnf &> /dev/null; then
            dnf makecache || true
        elif command -v yum &> /dev/null; then
            yum makecache || true
        fi
      register: update_cache
      ignore_errors: yes
      when: 
        - nginx_installed
        - not use_official_repo
    
    - name: Get current installed nginx package version
      shell: |
        rpm -q nginx
      register: nginx_current_package
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Get current installed nginx version (parsed)
      shell: |
        rpm -q --queryformat '%{VERSION}-%{RELEASE}' nginx 2>/dev/null || echo "Unknown"
      register: nginx_current_version_parsed
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Check current nginx module stream (Oracle Linux 8+)
      shell: |
        if command -v dnf &> /dev/null; then
            dnf module list nginx 2>/dev/null | grep -E "^nginx" | grep "\[e\]" | awk '{print $2}' | head -1 || echo "NoModuleStream"
        else
            echo "NoModuleStream"
        fi
      register: nginx_current_stream
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Determine target nginx stream from version
      set_fact:
        nginx_target_stream: >-
          {%- set target_ver = nginx_version_target | default('') | string -%}
          {%- if target_ver.startswith('1.20') or target_ver.startswith('1.21') -%}
            1.20
          {%- elif target_ver.startswith('1.22') or target_ver.startswith('1.23') -%}
            1.22
          {%- elif target_ver.startswith('1.24') or target_ver.startswith('1.25') -%}
            1.24
          {%- elif target_ver.startswith('1.26') or target_ver.startswith('1.27') -%}
            1.26
          {%- elif target_ver.startswith('1.18') or target_ver.startswith('1.19') -%}
            1.18
          {%- elif target_ver.startswith('1.16') or target_ver.startswith('1.17') -%}
            1.16
          {%- elif target_ver.startswith('1.14') or target_ver.startswith('1.15') -%}
            1.14
          {%- else -%}
            {{ nginx_current_stream.stdout | default('NoModuleStream') }}
          {%- endif -%}
      when: 
        - nginx_installed
        - nginx_version_target is defined
        - nginx_version_target != ''
    
    - name: Check if stream switching is needed
      set_fact:
        stream_switch_needed: >-
          {%- set current_stream = nginx_current_stream.stdout | default('NoModuleStream') | trim -%}
          {%- set target_stream = nginx_target_stream | default('') | trim -%}
          {%- if target_stream != '' and current_stream != 'NoModuleStream' and target_stream != current_stream -%}
            true
          {%- else -%}
            false
          {%- endif -%}
      when: 
        - nginx_installed
        - nginx_target_stream is defined
    
    - name: Reset nginx module stream
      shell: |
        dnf module reset -y nginx
      register: nginx_module_reset
      ignore_errors: yes
      when: 
        - nginx_installed
        - stream_switch_needed | default(false) | bool
        - not use_official_repo
    
    - name: Enable target nginx module stream
      shell: |
        dnf module enable -y nginx:{{ nginx_target_stream }}
      register: nginx_module_enable
      ignore_errors: yes
      when: 
        - nginx_installed
        - stream_switch_needed | default(false) | bool
        - not use_official_repo
        - nginx_module_reset is succeeded
    
    - name: Verify stream switch
      shell: |
        dnf module list nginx 2>/dev/null | grep -E "^nginx" | grep "\[e\]" | awk '{print $2}' | head -1 || echo "NoModuleStream"
      register: nginx_stream_after_switch
      ignore_errors: yes
      changed_when: false
      when: 
        - nginx_installed
        - stream_switch_needed | default(false) | bool
        - not use_official_repo
        - nginx_module_enable is defined
    
    - name: Check for available nginx updates
      shell: |
        if command -v dnf &> /dev/null; then
            if [ -n "{{ nginx_version_target | default('') }}" ]; then
                dnf list available nginx-{{ nginx_version_target }} 2>/dev/null | grep -E "^nginx" || echo "TARGET_VERSION:NotAvailable"
            else
                dnf check-update nginx 2>/dev/null | grep -E "^nginx" || echo "UPDATES:None"
            fi
        elif command -v yum &> /dev/null; then
            if [ -n "{{ nginx_version_target | default('') }}" ]; then
                yum list available nginx-{{ nginx_version_target }} 2>/dev/null | grep -E "^nginx" || echo "TARGET_VERSION:NotAvailable"
            else
                yum check-update nginx 2>/dev/null | grep -E "^nginx" || echo "UPDATES:None"
            fi
        fi
      register: nginx_updates_available
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Get available nginx package versions
      shell: |
        if command -v dnf &> /dev/null; then
            dnf list --showduplicates nginx 2>/dev/null | grep -E '^nginx'
        elif command -v yum &> /dev/null; then
            yum list --showduplicates nginx 2>/dev/null | grep -E '^nginx'
        else
            echo "No package manager found"
        fi
      register: nginx_available_versions
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Get latest available nginx version
      shell: |
        if command -v dnf &> /dev/null; then
            dnf list --showduplicates nginx 2>/dev/null | awk '/^nginx/ {print $2}' | sort -V | tail -1
        elif command -v yum &> /dev/null; then
            yum list --showduplicates nginx 2>/dev/null | awk '/^nginx/ {print $2}' | sort -V | tail -1
        else
            echo ""
        fi
      register: nginx_latest_version
      ignore_errors: yes
      changed_when: false
      when: nginx_installed
    
    - name: Determine if updates are available
      set_fact:
        updates_available: >-
          {%- set current_ver_raw = (nginx_current_version_parsed.stdout | default('') | trim) -%}
          {%- set latest_ver_raw = (nginx_latest_version.stdout | default('') | trim) -%}
          {%- set current_ver = current_ver_raw.split(':')[-1] if current_ver_raw != '' else '' -%}
          {%- set latest_ver = latest_ver_raw.split(':')[-1] if latest_ver_raw != '' else '' -%}
          {%- if 'UPDATES:None' in nginx_updates_available.stdout | default('') or 'TARGET_VERSION:NotAvailable' in nginx_updates_available.stdout | default('') -%}
            false
          {%- elif latest_ver != '' and current_ver != '' and latest_ver != current_ver -%}
            true
          {%- elif nginx_updates_available.stdout is defined and nginx_updates_available.stdout != '' and 'nginx' in nginx_updates_available.stdout and 'UPDATES:None' not in nginx_updates_available.stdout -%}
            true
          {%- else -%}
            false
          {%- endif -%}
      when: nginx_installed
    
    - name: Install nginx updates (from default repo)
      shell: |
        if command -v dnf &> /dev/null; then
            if [ -n "{{ nginx_version_target | default('') }}" ]; then
                dnf upgrade -y "nginx-{{ nginx_version_target }}" || dnf upgrade -y nginx
            else
                dnf upgrade -y nginx
            fi
        elif command -v yum &> /dev/null; then
            if [ -n "{{ nginx_version_target | default('') }}" ]; then
                yum upgrade -y "nginx-{{ nginx_version_target }}" || yum upgrade -y nginx
            else
                yum upgrade -y nginx
            fi
        else
            echo "ERROR: No package manager found (dnf/yum)"
            exit 1
        fi
      register: nginx_upgrade
      when: 
        - nginx_installed
        - install_updates | default(false) | bool
        - not use_official_repo
        - (updates_available or (stream_switch_needed | default(false)))
      ignore_errors: yes
    
    - name: Install nginx updates (from official repo)
      shell: |
        if command -v dnf &> /dev/null; then
            if [ -n "{{ nginx_version_target | default('') }}" ]; then
                dnf upgrade -y "nginx-{{ nginx_version_target }}" || dnf upgrade -y nginx
            else
                dnf upgrade -y nginx
            fi
        elif command -v yum &> /dev/null; then
            if [ -n "{{ nginx_version_target | default('') }}" ]; then
                yum upgrade -y "nginx-{{ nginx_version_target }}" || yum upgrade -y nginx
            else
                yum upgrade -y nginx
            fi
        else
            echo "ERROR: No package manager found (dnf/yum)"
            exit 1
        fi
      register: nginx_upgrade
      when: 
        - nginx_installed
        - install_updates | default(false) | bool
        - use_official_repo
      ignore_errors: yes
    
    - name: Get nginx version after patching
      shell: |
        nginx -v 2>&1 | head -1
      register: nginx_version_after
      ignore_errors: yes
      changed_when: false
      when: 
        - nginx_installed
        - install_updates | default(false) | bool
    
    - name: Restart nginx service if needed
      systemd:
        name: nginx
        state: restarted
      when: 
        - nginx_installed
        - install_updates | default(false) | bool
        - nginx_upgrade is succeeded
      ignore_errors: yes
    
    - name: Display patching summary
      debug:
        msg:
          - "=========================================="
          - "Nginx Patching Summary"
          - "Host: {{ inventory_hostname }}"
          - "Version Before: {{ nginx_version_before.stdout | default('Unknown') }}"
          - "Version After: {{ nginx_version_after.stdout | default('Unknown') if (install_updates | default(false)) else 'N/A' }}"
          - "Updates Available: {{ 'Yes' if updates_available else 'No' }}"
          - "Updates Installed: {{ 'Yes' if (install_updates | default(false) and nginx_upgrade is succeeded) else 'No' }}"
          - "Service Status: {{ nginx_service_status_before.stdout | default('Unknown') }}"
          - "=========================================="
      when: nginx_installed
