---
- name: Patch Windows Server with WSUS
  hosts: all
  gather_facts: yes
  # wsus_server can be set in AWX as an extra variable
  #   - Format: wsus_server: "http://wsus-server.domain.com:8530" or "https://wsus-server.domain.com:8531"
  #   - If not set, will use default Windows Update settings
  #
  # install_updates can be set in AWX as an extra variable
  #   - true: Install available updates (default: false - only check)
  #   - false: Only check for available updates without installing
  #
  # reboot_if_needed can be set in AWX as an extra variable
  #   - true: Automatically reboot if required after updates (default: false)
  #   - false: Do not reboot automatically
  #
  # update_categories can be set in AWX as an extra variable or survey
  # Examples:
  #   - List: ["SecurityUpdates", "UpdateRollups", "CriticalUpdates"]
  #   - Empty/not set: [] or leave unset (will check all update categories)
  #   Valid categories: SecurityUpdates, UpdateRollups, CriticalUpdates, DefinitionUpdates, FeaturePacks, ServicePacks, Tools, Updates
  #
  # services_to_check can be set in AWX as an extra variable
  # Examples:
  #   - "IIS" - Check IIS only
  #   - "SQL Server" - Check SQL Server only
  #   - "IIS,SQL Server" - Check both IIS and SQL Server
  #   - "IIS,SQL Server,Exchange" - Check multiple services
  #   - Empty/not set: Skip service checks (patch all)
  
  tasks:
    - name: Get formatted date and time
      set_fact:
        patch_date: "{{ ansible_date_time.date.split('-') | reverse | join('/') }}"
        patch_time: "{{ ansible_date_time.time }}"
    
    - name: Parse services to check
      set_fact:
        services_list: "{{ services_to_check.split(',') | map('trim') | list if services_to_check is defined and services_to_check | length > 0 else [] }}"
    
    - name: Check installed services and versions
      win_shell: |
        $services = @()
        $checkServices = "{{ services_list | join(',') }}"
        
        if ([string]::IsNullOrEmpty($checkServices)) {
            Write-Output "NO_SERVICES_SPECIFIED"
            exit 0
        }
        
        $serviceArray = $checkServices -split ','
        
        foreach ($svc in $serviceArray) {
            $svc = $svc.Trim()
            $result = @{
                Name = $svc
                Installed = $false
                Version = "Unknown"
                Status = "Not Found"
            }
            
            switch ($svc) {
                "IIS" {
                    $feature = Get-WindowsFeature -Name Web-Server -ErrorAction SilentlyContinue
                    if ($feature -and $feature.Installed) {
                        $result.Installed = $true
                        $result.Status = "Installed"
                        try {
                            Import-Module WebAdministration -ErrorAction SilentlyContinue
                            $iisVersion = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\InetStp" -ErrorAction SilentlyContinue).VersionString
                            if ($iisVersion) {
                                $result.Version = $iisVersion
                            }
                        } catch {}
                    }
                }
                "SQL Server" {
                    $sqlServices = Get-Service -Name "MSSQL*" -ErrorAction SilentlyContinue
                    if ($sqlServices) {
                        $result.Installed = $true
                        $result.Status = "Installed"
                        try {
                            $sqlVersion = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL" -ErrorAction SilentlyContinue)
                            if ($sqlVersion) {
                                $instanceName = $sqlVersion.PSObject.Properties.Name | Select-Object -First 1
                                $result.Version = $instanceName
                            }
                        } catch {}
                    }
                }
                "Exchange" {
                    $exchService = Get-Service -Name "MSExchangeServiceHost" -ErrorAction SilentlyContinue
                    if ($exchService) {
                        $result.Installed = $true
                        $result.Status = "Installed"
                        try {
                            $exchVersion = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\Setup" -ErrorAction SilentlyContinue).MsiProductMajor
                            if ($exchVersion) {
                                $result.Version = $exchVersion
                            }
                        } catch {}
                    }
                }
                default {
                    # Generic service check
                    $genericService = Get-Service -Name "*$svc*" -ErrorAction SilentlyContinue | Select-Object -First 1
                    if ($genericService) {
                        $result.Installed = $true
                        $result.Status = $genericService.Status
                    }
                }
            }
            
            Write-Output "SERVICE:$($result.Name)|INSTALLED:$($result.Installed)|VERSION:$($result.Version)|STATUS:$($result.Status)"
        }
      register: services_check
      when: services_list | length > 0
      ignore_errors: yes
    
    - name: Display services check results
      debug:
        msg: "{{ services_check.stdout_lines | default(['No services specified to check']) }}"
    
    - name: Get Windows version and build
      win_shell: |
        $os = Get-CimInstance Win32_OperatingSystem
        Write-Output "OS:$($os.Caption) Build:$($os.BuildNumber)"
      register: windows_info
    
    - name: Check current WSUS configuration
      win_shell: |
        $regPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate"
        $auPath = "$regPath\AU"
        
        if (Test-Path $regPath) {
            $wsusServer = (Get-ItemProperty -Path $regPath -Name WUServer -ErrorAction SilentlyContinue).WUServer
            $wsusStatusServer = (Get-ItemProperty -Path $regPath -Name WUStatusServer -ErrorAction SilentlyContinue).WUStatusServer
            $useWUServer = (Get-ItemProperty -Path $auPath -Name UseWUServer -ErrorAction SilentlyContinue).UseWUServer
            
            Write-Output "WSUS_SERVER:$wsusServer"
            Write-Output "WSUS_STATUS_SERVER:$wsusStatusServer"
            Write-Output "USE_WSUS:$useWUServer"
        } else {
            Write-Output "WSUS_NOT_CONFIGURED"
        }
      register: wsus_config_check
      ignore_errors: yes
    
    - name: Set WSUS server variable
      set_fact:
        wsus_server_url: "{{ wsus_server | default('') }}"
    
    - name: Ensure WSUS policy key exists
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        state: present
      when: wsus_server_url | length > 0
    
    - name: Ensure WSUS AU subkey exists
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
        state: present
      when: wsus_server_url | length > 0
    
    - name: Configure WSUS server URLs
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        name: "{{ item }}"
        data: "{{ wsus_server_url }}"
        type: string
      loop:
        - WUServer
        - WUStatusServer
      when: wsus_server_url | length > 0
    
    - name: Configure automatic update settings
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: "{{ item.name }}"
        data: "{{ item.value }}"
        type: dword
      loop:
        - { name: UseWUServer, value: 1 }
        - { name: AUOptions, value: 4 }
      when: wsus_server_url | length > 0
    
    - name: Restart Windows Update service to apply WSUS settings
      win_service:
        name: wuauserv
        state: restarted
      when: wsus_server_url | length > 0
    
    - name: Display patching information
      debug:
        msg:
          - "=========================================="
          - "Windows WSUS Patching Information"
          - "Date: {{ patch_date }}"
          - "Time: {{ patch_time }}"
          - "Host: {{ inventory_hostname }}"
          - "Windows: {{ windows_info.stdout }}"
          - "Services to Check: {{ services_to_check | default('None - Patch all') }}"
          - "Services Status: {{ services_check.stdout_lines | default(['No services specified']) }}"
          - "WSUS Server: {{ wsus_server | default('Default Windows Update') }}"
          - "WSUS Config: {{ wsus_config_check.stdout_lines | default([]) }}"
          - "Install Updates: {{ install_updates | default(false) }}"
          - "Reboot If Needed: {{ reboot_if_needed | default(false) }}"
          - "Update Categories: {{ 'All categories' if (update_categories is not defined or update_categories | length == 0) else update_categories }}"
          - "=========================================="
    
    - name: Check Windows Update service status
      win_shell: |
        $service = Get-Service -Name wuauserv -ErrorAction SilentlyContinue
        if ($service) {
            Write-Output "STATUS:$($service.Status)"
            if ($service.Status -ne 'Running') {
                Start-Service -Name wuauserv -ErrorAction SilentlyContinue
                Start-Sleep -Seconds 2
                $service = Get-Service -Name wuauserv
                Write-Output "STATUS_AFTER:$($service.Status)"
            }
        } else {
            Write-Output "STATUS:NotFound"
        }
      register: wuauserv_status
      ignore_errors: yes
    
    - name: Search for available updates from WSUS
      win_updates:
        category_names: "{{ update_categories | default(omit) }}"
        state: searched
        log_path: C:\ansible_wsus_updates.log
      register: available_updates
    
    - name: Display available updates
      debug:
        msg:
          - "=========================================="
          - "Available Windows Updates from WSUS"
          - "Total Updates Found: {{ available_updates.found_update_count | default(0) }}"
          - "=========================================="
    
    - name: Display update details
      debug:
        msg: 
          - "Title: {{ item.title }}"
          - "KB: {{ item.kb | default('N/A') }}"
          - "ID: {{ item.id }}"
          - "Categories: {{ item.categories | default([]) | join(', ') }}"
      loop: "{{ available_updates.updates | default([], true) }}"
      when: available_updates.found_update_count | default(0) > 0
    
    - name: Install Windows updates from WSUS
      win_updates:
        category_names: "{{ update_categories | default(omit) }}"
        state: installed
        log_path: C:\ansible_wsus_updates.log
        server_selection: "managed_server"
        reboot: no
      register: install_result
      when: 
        - install_updates | default(false) | bool
        - available_updates.found_update_count | default(0) > 0
      ignore_errors: yes
    
    - name: Check if reboot is required
      win_shell: |
        $rebootRequired = $false
        
        # Check Component Based Servicing
        if (Test-Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending") {
            $rebootRequired = $true
        }
        
        # Check Windows Update
        if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired") {
            $rebootRequired = $true
        }
        
        # Check PendingFileRenameOperations
        $pendingFileRename = Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager" -Name PendingFileRenameOperations -ErrorAction SilentlyContinue
        if ($pendingFileRename) {
            $rebootRequired = $true
        }
        
        if ($rebootRequired) {
            Write-Output "REQUIRED:Yes"
        } else {
            Write-Output "REQUIRED:No"
        }
      register: reboot_check
      when: install_updates | default(false) | bool
      ignore_errors: yes
    
    - name: Reboot server if needed
      win_reboot:
        reboot_timeout: 3600
        pre_reboot_delay: 60
        post_reboot_delay: 120
        test_command: whoami
      when:
        - install_updates | default(false) | bool
        - reboot_if_needed | default(false) | bool
        - "'Yes' in (reboot_check.stdout | default(''))"
    
    - name: Verify services are running after updates
      win_shell: |
        $services = @()
        $checkServices = "{{ services_list | join(',') }}"
        
        if ([string]::IsNullOrEmpty($checkServices)) {
            Write-Output "NO_SERVICES_TO_VERIFY"
            exit 0
        }
        
        $serviceArray = $checkServices -split ','
        
        foreach ($svc in $serviceArray) {
            $svc = $svc.Trim()
            
            switch ($svc) {
                "IIS" {
                    $service = Get-Service -Name W3SVC -ErrorAction SilentlyContinue
                    if ($service) {
                        if ($service.Status -ne 'Running') {
                            Start-Service -Name W3SVC -ErrorAction SilentlyContinue
                            Start-Sleep -Seconds 3
                            $service = Get-Service -Name W3SVC
                        }
                        Write-Output "SERVICE:IIS|STATUS:$($service.Status)"
                    } else {
                        Write-Output "SERVICE:IIS|STATUS:NotFound"
                    }
                }
                "SQL Server" {
                    $sqlServices = Get-Service -Name "MSSQL*" -ErrorAction SilentlyContinue
                    foreach ($sqlSvc in $sqlServices) {
                        if ($sqlSvc.Status -ne 'Running' -and $sqlSvc.StartType -ne 'Disabled') {
                            Start-Service -Name $sqlSvc.Name -ErrorAction SilentlyContinue
                            Start-Sleep -Seconds 3
                        }
                        $sqlSvc = Get-Service -Name $sqlSvc.Name
                        Write-Output "SERVICE:$($sqlSvc.DisplayName)|STATUS:$($sqlSvc.Status)"
                    }
                }
                "Exchange" {
                    $exchServices = Get-Service -Name "MSExchange*" -ErrorAction SilentlyContinue
                    foreach ($exchSvc in $exchServices) {
                        if ($exchSvc.Status -ne 'Running' -and $exchSvc.StartType -ne 'Disabled') {
                            Start-Service -Name $exchSvc.Name -ErrorAction SilentlyContinue
                            Start-Sleep -Seconds 2
                        }
                        $exchSvc = Get-Service -Name $exchSvc.Name
                        Write-Output "SERVICE:$($exchSvc.DisplayName)|STATUS:$($exchSvc.Status)"
                    }
                }
                default {
                    $genericService = Get-Service -Name "*$svc*" -ErrorAction SilentlyContinue | Select-Object -First 1
                    if ($genericService) {
                        if ($genericService.Status -ne 'Running' -and $genericService.StartType -ne 'Disabled') {
                            Start-Service -Name $genericService.Name -ErrorAction SilentlyContinue
                            Start-Sleep -Seconds 2
                        }
                        $genericService = Get-Service -Name $genericService.Name
                        Write-Output "SERVICE:$($genericService.DisplayName)|STATUS:$($genericService.Status)"
                    }
                }
            }
        }
      register: services_status_check
      when: 
        - install_updates | default(false) | bool
        - services_list | length > 0
      ignore_errors: yes
    
    - name: Display installed updates
      debug:
        msg: 
          - "Title: {{ item.title }}"
          - "KB: {{ item.kb | default('N/A') }}"
          - "ID: {{ item.id }}"
      loop: "{{ install_result.updates | default([], true) }}"
      when: 
        - install_updates | default(false) | bool
        - install_result.updates is defined
        - install_result.updates | length > 0
    
    - name: Display patching summary
      debug:
        msg:
          - "=========================================="
          - "Windows WSUS Patching Summary"
          - "Date: {{ patch_date }}"
          - "Time: {{ patch_time }}"
          - "Host: {{ inventory_hostname }}"
          - "WSUS Server: {{ wsus_server | default('Default Windows Update') }}"
          - "Services Checked: {{ services_to_check | default('None - Patch all') }}"
          - "Services Status (Before): {{ services_check.stdout_lines | default(['N/A']) }}"
          - "Services Status (After): {{ services_status_check.stdout_lines | default(['N/A']) }}"
          - "Available Updates: {{ available_updates.found_update_count | default(0) }}"
          - "Updates Installed: {{ install_result.installed_update_count | default(0) if install_updates | default(false) else 0 }}"
          - "Reboot Required: {{ 'Yes' if ('Yes' in (reboot_check.stdout | default(''))) else 'No' if install_updates | default(false) else 'N/A' }}"
          - "=========================================="

