---
- name: Restore Hyper-V VM from Snapshot
  hosts: all
  gather_facts: no
  vars:
    skip_verify: true

  tasks:
    - name: Validate required variables
      fail:
        msg: "Both vm_name and snapshot_name are required"
      when: >
        (vm_name is not defined or vm_name == "" or vm_name | trim == "") or
        (snapshot_name is not defined or snapshot_name == "" or snapshot_name | trim == "")

    - name: Restore VM from snapshot (this may take several minutes)
      ansible.windows.win_shell: |
        $result = @{
          status = 'FAILED'
          message = ''
        }

        try {
          Restore-VMSnapshot -VMName '{{ vm_name }}' -Name '{{ snapshot_name }}' -Confirm:$false -ErrorAction Stop | Out-Null
          $result.status = 'SUCCESS'
        }
        catch {
          $result.message = $_.Exception.Message
        }

        $result | ConvertTo-Json -Compress | Write-Output
      register: restore_result

      changed_when: >
        ((restore_result.stdout | default('{}')) | from_json).status == 'SUCCESS'

    - name: Check restore status
      fail:
        msg: >
          Restore operation failed: {{
            ((restore_result.stdout | default('{}')) | from_json).message | default('Unknown error')
          }}
      when:
        - not (skip_verify | bool)
        - restore_result.rc is defined
        - restore_result.rc != 0

    - name: Display result
      debug:
        msg: "VM '{{ vm_name }}' has been restored from snapshot '{{ snapshot_name }}' successfully"
