---
- name: Restore Hyper-V VM from Snapshot
  hosts: all
  gather_facts: no
  tasks:
    - name: Validate required variables
      fail:
        msg: "Both vm_name and snapshot_name are required"
      when: >
        (vm_name is not defined or vm_name == "" or vm_name | trim == "") or
        (snapshot_name is not defined or snapshot_name == "" or snapshot_name | trim == "")
      
    - name: Restore VM from snapshot
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $vmName = @"
        {{ vm_name }}
        "@.Trim()
        $snapshotName = @"
        {{ snapshot_name }}
        "@.Trim()
        try {
            Restore-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false -ErrorAction Stop | Out-Null
            Write-Output "SUCCESS: VM restored from snapshot"
        } catch {
            Write-Output "ERROR: $($_.Exception.Message)"
            throw
        }
      register: restore_result
      changed_when: true
      
    - name: Display result
      debug:
        msg: "{{ restore_result.stdout_lines }}"

