---
- name: Restore Hyper-V VM from Snapshot
  hosts: hyperv_hosts
  gather_facts: no
  vars:
    vm_name: ""  # Required: VM name
    snapshot_name: ""  # Required: Snapshot name to restore
    
  tasks:
    - name: Validate required variables
      fail:
        msg: "Both vm_name and snapshot_name are required"
      when: vm_name == "" or snapshot_name == ""
      
    - name: Restore VM from snapshot
      win_shell: |
        $vmName = "{{ vm_name }}"
        $snapshotName = "{{ snapshot_name }}"
        
        try {
            Restore-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false
            Write-Output "SUCCESS: VM '$vmName' restored from snapshot '$snapshotName'"
        } catch {
            Write-Output "ERROR: Failed to restore snapshot - $_"
            exit 1
        }
      register: restore_result
      
    - name: Display result
      debug:
        msg: "{{ restore_result.stdout }}"

