---
- name: Restore Hyper-V VM from Snapshot
  hosts: all
  gather_facts: no
  tasks:
    - name: Validate required variables
      fail:
        msg: "Both vm_name and snapshot_name are required"
      when: >
        (vm_name is not defined or vm_name == "" or vm_name | trim == "") or
        (snapshot_name is not defined or snapshot_name == "" or snapshot_name | trim == "")
      
    - name: Restore VM from snapshot (this may take several minutes)
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $VerbosePreference = 'SilentlyContinue'
        $WarningPreference = 'SilentlyContinue'
        $vmName = '{{ vm_name }}'
        $snapshotName = '{{ snapshot_name }}'
        Write-Host "Starting restore operation..."
        $null = Restore-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false
        Write-Host "SUCCESS: Restore completed"
      register: restore_result
      async: 1800
      poll: 10
      
    - name: Display result
      debug:
        msg: "{{ restore_result.stdout_lines }}"

