---
- name: Restore Hyper-V VM from Snapshot
  hosts: all
  gather_facts: no
  tasks:
    - name: Validate required variables
      fail:
        msg: "Both vm_name and snapshot_name are required"
      when: >
        (vm_name is not defined or vm_name == "" or vm_name | trim == "") or
        (snapshot_name is not defined or snapshot_name == "" or snapshot_name | trim == "")
      
    - name: Restore VM from snapshot (this may take several minutes)
      win_shell: |
        $ErrorActionPreference = 'Stop'
        $vmName = '{{ vm_name }}'
        $snapshotName = '{{ snapshot_name }}'
        try {
          Restore-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false -ErrorAction Stop | Out-Null
          $result = @{
            status = 'success'
            vm = $vmName
            snapshot = $snapshotName
          }
          $result | ConvertTo-Json -Compress
        } catch {
          $result = @{
            status = 'error'
            vm = $vmName
            snapshot = $snapshotName
            message = $_.Exception.Message
          }
          $result | ConvertTo-Json -Compress
          exit 1
        }
      register: restore_result
      changed_when: restore_result.rc == 0
      failed_when: restore_result.rc != 0
      
    - name: Parse restore result
      set_fact:
        restore_output: "{{ restore_result.stdout | default('{}') | trim | from_json }}"
      
    - name: Display result
      debug:
        msg: "{{ (restore_output.status | default('UNKNOWN') | upper) ~ ': VM ' ~ (restore_output.vm | default(vm_name)) ~ ' snapshot ' ~ (restore_output.snapshot | default(snapshot_name)) }}"

