---
- name: Restore Hyper-V VM from Snapshot
  hosts: all
  gather_facts: no
  tasks:
    - name: Validate required variables
      fail:
        msg: "Both vm_name and snapshot_name are required"
      when: >
        (vm_name is not defined or vm_name == "" or vm_name | trim == "") or
        (snapshot_name is not defined or snapshot_name == "" or snapshot_name | trim == "")
      
    - name: Restore VM from snapshot
      win_shell: |
        $ErrorActionPreference = 'Stop'
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $ProgressPreference = 'SilentlyContinue'
        
        $vmName = @"
        {{ vm_name }}
        "@.Trim()
        
        $snapshotName = @"
        {{ snapshot_name }}
        "@.Trim()
        
        try {
            Restore-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false | Out-Null
            Write-Host "SUCCESS: VM '$vmName' restored from snapshot '$snapshotName'"
            exit 0
        } catch {
            Write-Host "ERROR: Failed to restore snapshot for '$vmName' from '$snapshotName' - $($_.Exception.Message)"
            exit 1
        }
      register: restore_result
      changed_when: restore_result.rc == 0
      failed_when: false
      
    - name: Display result
      debug:
        msg: "{{ restore_result.stdout_lines | default(['No output received']) }}"
        
    - name: Fail if restore failed
      fail:
        msg: "Restore operation failed: {{ restore_result.stdout_lines | join(' ') }}"
      when: restore_result.rc != 0

