---
- name: Restore Hyper-V VM from Snapshot
  hosts: all
  gather_facts: no
  tasks:
    - name: Validate required variables
      fail:
        msg: "Both vm_name and snapshot_name are required"
      when: >
        (vm_name is not defined or vm_name == "" or vm_name | trim == "") or
        (snapshot_name is not defined or snapshot_name == "" or snapshot_name | trim == "")
      
    - name: Restore VM from snapshot (this may take several minutes)
      win_shell: |
        Restore-VMSnapshot -VMName '{{ vm_name }}' -Name '{{ snapshot_name }}' -Confirm:$false
        Write-Output "Restore completed successfully"
      register: restore_result
      no_log: true
      
    - name: Display result
      debug:
        msg: "{{ restore_result.stdout | default('VM restored successfully') }}"

