- name: Restore Last Hyper-V VM Snapshots
  hosts: all
  gather_facts: no
  # vm_names can be set in AWX as an extra variable or survey
  # Examples:
  #   - String from survey: vm_names: "vm1,vm2" or vm_names: "vm1"
  #   - List: vm_names: ["vm1", "vm2"]
  #   - Empty/not set: vm_names: "" or leave unset (will restore last snapshot for all VMs)
  # stop_vm_if_running: true (default) - Stop VM before restore if it's running
  # start_vm_after_restore: true (default) - Start VM after restore completes
  tags:
    - restore-snapshot
  
  vars:
    # Explicitly set test_fail to false to prevent interference from global variables
    test_fail: false
    
  tasks:
    - name: Set default vm_names if not defined
      set_fact:
        vm_names: ""
      when: vm_names is not defined
    
    - name: Set default stop_vm_if_running
      set_fact:
        stop_vm_if_running: true
      when: stop_vm_if_running is not defined
    
    - name: Set default start_vm_after_restore
      set_fact:
        start_vm_after_restore: true
      when: start_vm_after_restore is not defined
    
    - name: Normalize vm_names to a list (handle string from AWX survey)
      set_fact:
        vm_names_normalized: "{{ vm_names.split(',') | map('trim') | select | list }}"
      when: vm_names is defined and vm_names is string and vm_names != '' and ',' in vm_names
      
    - name: Normalize vm_names to a list (single VM)
      set_fact:
        vm_names_normalized: "{{ [vm_names | trim] }}"
      when: vm_names is defined and vm_names is string and vm_names != '' and ',' not in vm_names
      
    - name: Normalize vm_names to a list (already a list)
      set_fact:
        vm_names_normalized: "{{ vm_names | list }}"
      when: vm_names is defined and vm_names is iterable and vm_names is not string
      
    - name: Set empty list if vm_names is empty
      set_fact:
        vm_names_normalized: []
      when: vm_names is not defined or vm_names == '' or vm_names == None
      
    - name: Get all VMs if no specific VMs specified
      win_shell: |
        $ErrorActionPreference = 'Stop'
        try {
            $vms = @(Get-VM | Select-Object -ExpandProperty Name)
            if ($vms.Count -eq 0) {
                Write-Output '[]'
            } elseif ($vms.Count -eq 1) {
                Write-Output "[`"$($vms[0])`"]"
            } else {
                $vms | ConvertTo-Json -Compress
            }
        } catch {
            Write-Output '[]'
        }
      register: all_vms
      when: vm_names_normalized | length == 0
      changed_when: false
      
    - name: Set VM list from all VMs
      set_fact:
        target_vms: "{{ (all_vms.stdout | default('[]') | trim | from_json) if (all_vms.stdout is defined and all_vms.stdout != '' and all_vms.stdout != '[]') else [] }}"
      when: vm_names_normalized | length == 0
      ignore_errors: yes
    
    - name: Set default target_vms if empty
      set_fact:
        target_vms: []
      when: 
        - vm_names_normalized | length == 0
        - target_vms is not defined or target_vms | length == 0
      
    - name: Set VM list from provided names
      set_fact:
        target_vms: "{{ vm_names_normalized }}"
      when: vm_names_normalized | length > 0
      
    - name: Validate target_vms is set
      set_fact:
        target_vms: []
      when: target_vms is not defined
      
    - name: Display VMs to restore last snapshot
      debug:
        msg: "Restoring last snapshot for VMs: {{ target_vms | default([]) }}"
    
    - name: Fail if no VMs found
      fail:
        msg: "No VMs found to restore snapshots. Please check VM names or ensure Hyper-V has VMs available."
      when: target_vms is not defined or target_vms | length == 0
        
    - name: List all snapshots for target VMs
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $ErrorActionPreference = 'Stop'
        $vmName = "{{ item | replace('"', '`"') }}"
        
        try {
            # Get VM
            $vm = Get-VM -Name $vmName -ErrorAction Stop
            
            # Get all snapshots for this VM, sorted by creation time (oldest first for display)
            $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue | 
                          Sort-Object CreationTime)
            
            if ($snapshots.Count -eq 0) {
                Write-Output "VM: $vmName - No snapshots found"
            } else {
                Write-Output "VM: $vmName - Total snapshots: $($snapshots.Count)"
                foreach ($snapshot in $snapshots) {
                    $creationTime = $snapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss')
                    Write-Output "  - $($snapshot.Name) (Created: $creationTime)"
                }
            }
        }
        catch {
            Write-Output "VM: $vmName - ERROR: $($_.Exception.Message)"
        }
      loop: "{{ target_vms | default([]) }}"
      register: list_snapshots_results
      changed_when: false
      failed_when: false
      when: target_vms is defined and target_vms | length > 0
      
    - name: Display all snapshots
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ list_snapshots_results.results }}"
      loop_control:
        label: "{{ item.item }}"
        
    - name: Identify last (most recent) snapshot for each VM
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $ErrorActionPreference = 'Stop'
        $vmName = "{{ item | replace('"', '`"') }}"
        
        try {
            # Get all snapshots for this VM, sorted by creation time (most recent first)
            $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue | 
                          Sort-Object CreationTime -Descending)
            
            if ($snapshots.Count -eq 0) {
                Write-Output "VM: $vmName - No snapshots to restore"
            } else {
                $lastSnapshot = $snapshots[0]
                $creationTime = $lastSnapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss')
                Write-Output "VM: $vmName - Last snapshot to be restored: '$($lastSnapshot.Name)' (Created: $creationTime)"
            }
        }
        catch {
            Write-Output "VM: $vmName - ERROR: $($_.Exception.Message)"
        }
      loop: "{{ target_vms | default([]) }}"
      register: last_snapshot_info
      changed_when: false
      failed_when: false
      when: target_vms is defined and target_vms | length > 0
      
    - name: Display last snapshots that will be restored
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ last_snapshot_info.results }}"
      loop_control:
        label: "{{ item.item }}"
        
    - name: Restore last snapshot for each VM
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $ErrorActionPreference = 'Continue'
        $WarningPreference = 'SilentlyContinue'
        $vmName = "{{ item | replace('"', '`"') }}"
        
        # Ensure we always have output
        Write-Output "Starting restore process for VM: $vmName"
        
        try {
            $stopVm = [System.Convert]::ToBoolean("{{ stop_vm_if_running | lower }}")
        } catch {
            $stopVm = $true
        }
        
        try {
            $startVm = [System.Convert]::ToBoolean("{{ start_vm_after_restore | lower }}")
        } catch {
            $startVm = $true
        }
        
        try {
            # Get VM
            $vm = $null
            try {
                $vm = Get-VM -Name $vmName -ErrorAction Stop 
            } catch {
                Write-Output "ERROR: VM '$vmName' not found: $($_.Exception.Message)"
                exit 1
            }
            
            if ($null -eq $vm) {
                Write-Output "ERROR: VM '$vmName' not found"
                exit 1
            }
            
            $vmState = $vm.State
            Write-Output "INFO: VM '$vmName' current state: $vmState"
            
            # Get all snapshots for this VM, sorted by creation time (most recent first)
            $snapshots = @()
            try {
                $snapshots = @(Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue | 
                              Sort-Object CreationTime -Descending)
            } catch {
                Write-Output "WARNING: Error getting snapshots for VM '$vmName': $($_.Exception.Message)"
                $snapshots = @()
            }
            
            if ($snapshots.Count -eq 0) {
                Write-Output "NO_SNAPSHOTS: No snapshots found for VM '$vmName'"
                exit 0
            }
            
            # Get the last (most recent) snapshot
            $lastSnapshot = $snapshots[0]
            if ($null -eq $lastSnapshot) {
                Write-Output "ERROR: Failed to get last snapshot for VM '$vmName'"
                exit 1
            }
            
            $snapshotName = $lastSnapshot.Name
            $creationTime = $lastSnapshot.CreationTime.ToString('yyyy-MM-dd HH:mm:ss')
            Write-Output "INFO: Target snapshot: '$snapshotName' (Created: $creationTime)"
            
            # Stop VM if running and stop_vm_if_running is true
            $vmStopped = $false
            if ($stopVm) {
                try {
                    $vm = Get-VM -Name $vmName -ErrorAction Stop
                    if ($vm.State -eq 'Running') {
                        Write-Output "INFO: Stopping VM '$vmName'..."
                        Stop-VM -VM $vm -Force -Confirm:$false -ErrorAction Stop | Out-Null
                        Start-Sleep -Seconds 2
                        $vm = Get-VM -Name $vmName -ErrorAction Stop
                        if ($vm.State -eq 'Off') {
                            $vmStopped = $true
                            Write-Output "INFO: VM stopped successfully"
                        } else {
                            Write-Output "WARNING: VM may not have stopped completely. Current state: $($vm.State)"
                        }
                    } else {
                        Write-Output "INFO: VM is not running (State: $($vm.State)), skipping stop"
                    }
                } catch {
                    Write-Output "ERROR: Failed to stop VM '$vmName': $($_.Exception.Message)"
                    exit 1
                }
            }
            
            # Restore the last snapshot
            try {
                Write-Output "INFO: Restoring snapshot '$snapshotName'..."
                Restore-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false -ErrorAction Stop | Out-Null
                Write-Output "INFO: Snapshot restored successfully"
            } catch {
                Write-Output "ERROR: Failed to restore snapshot '$snapshotName' for VM '$vmName': $($_.Exception.Message)"
                exit 1
            }
            
            # Start VM if requested
            if ($startVm) {
                try {
                    Write-Output "INFO: Starting VM '$vmName'..."
                    Start-VM -Name $vmName -ErrorAction Stop | Out-Null
                    Start-Sleep -Seconds 3
                    $vm = Get-VM -Name $vmName -ErrorAction Stop
                    if ($vm.State -eq 'Running') {
                        Write-Output "INFO: VM started successfully"
                    } else {
                        Write-Output "WARNING: VM may not have started completely. Current state: $($vm.State)"
                    }
                } catch {
                    Write-Output "ERROR: Failed to start VM '$vmName': $($_.Exception.Message)"
                    exit 1
                }
            }
            
            Write-Output "SUCCESS: Restored last snapshot '$snapshotName' (created: $creationTime) for VM '$vmName'"
            Write-Output "COMPLETED: Restore operation finished for VM '$vmName'"
            exit 0
        }
        catch {
            $errorMsg = $_.Exception.Message
            if ([string]::IsNullOrEmpty($errorMsg)) {
                $errorMsg = "Unknown error occurred"
            }
            Write-Output "ERROR: Failed to restore snapshot for VM '$vmName': $errorMsg"
            exit 1
        }
      loop: "{{ target_vms | default([]) }}"
      register: restore_results
      when: target_vms is defined and target_vms | length > 0
      ignore_errors: yes
      failed_when: false
      changed_when: 
        - restore_results.stdout is defined
        - restore_results.stdout != ''
        - "'SUCCESS' in restore_results.stdout"
      
    - name: Display restore summary
      debug:
        msg: "{{ item.stdout_lines | default(['No output']) if item.stdout_lines is defined and item.stdout_lines | length > 0 else ['No output available'] }}"
      loop: "{{ restore_results.results | default([]) }}"
      loop_control:
        label: "{{ item.item | default('Unknown') }}"
      when: 
        - restore_results is defined
        - restore_results.results is defined
        - restore_results.results | length > 0
      ignore_errors: yes
    
    - name: Display restore completion status
      debug:
        msg:
          - "=========================================="
          - "Restore Operation Summary"
          - "Total VMs processed: {{ restore_results.results | default([]) | length }}"
          - "=========================================="
      when: restore_results is defined and restore_results.results is defined
      ignore_errors: yes

