- name: Restore Hyper-V VM Snapshot
  hosts: all
  gather_facts: no
  vars:
    vm_name: ""  # Required: VM name to restore
    snapshot_name: ""  # Required: Snapshot name to restore
    stop_vm_if_running: true  # Stop VM before restore if it's running
    start_vm_after_restore: true  # Start VM after restore completes

  tasks:
    - name: Validate required variables
      fail:
        msg: "vm_name and snapshot_name are required."
      when: vm_name | length == 0 or snapshot_name | length == 0

    - name: Ensure snapshot exists
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $vmName = "{{ vm_name | replace('"', '`"') }}"
        $snapshotName = "{{ snapshot_name | replace('"', '`"') }}"
        $null = Get-VM -Name $vmName -ErrorAction Stop
        $snapshot = Get-VMSnapshot -VMName $vmName -Name $snapshotName -ErrorAction Stop
        if (-not $snapshot) {
            throw "Snapshot '$snapshotName' not found for VM '$vmName'."
        }
        "FOUND"
      register: snapshot_check

    - name: Stop VM if running
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $vmName = "{{ vm_name | replace('"', '`"') }}"
        $vm = Get-VM -Name $vmName -ErrorAction Stop
        if ($vm.State -eq 'Running') {
            Stop-VM -VM $vm -Force -Confirm:$false -ErrorAction Stop | Out-Null
            "STOPPED"
        } else {
            "ALREADY_STOPPED"
        }
      register: stop_vm_result
      when: stop_vm_if_running
      changed_when: stop_vm_result.stdout is search("STOPPED")

    - name: Restore snapshot
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $vmName = "{{ vm_name | replace('"', '`"') }}"
        $snapshotName = "{{ snapshot_name | replace('"', '`"') }}"
        Restore-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false -ErrorAction Stop | Out-Null
        "RESTORED"
      register: restore_result

    - name: Start VM after restore
      win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        $vmName = "{{ vm_name | replace('"', '`"') }}"
        Start-VM -Name $vmName -ErrorAction Stop | Out-Null
        "STARTED"
      register: start_vm_result
      when: start_vm_after_restore
      changed_when: start_vm_result.stdout is search("STARTED")

    - name: Display restore summary
      debug:
        msg:
          vm_name: "{{ vm_name }}"
          snapshot_name: "{{ snapshot_name }}"
          stop_vm: "{{ stop_vm_result.stdout | default('SKIPPED') }}"
          restore: "{{ restore_result.stdout }}"
          start_vm: "{{ start_vm_result.stdout | default('SKIPPED') }}"

