---
- name: Restore Hyper-V VM from Snapshot
  hosts: all
  gather_facts: no
  tasks:
    - name: Validate required variables
      fail:
        msg: "Both vm_name and snapshot_name are required"
      when: >
        (vm_name is not defined or vm_name == "" or vm_name | trim == "") or
        (snapshot_name is not defined or snapshot_name == "" or snapshot_name | trim == "")
      
    - name: Restore VM from snapshot
      win_shell: |
        try {
          $ProgressPreference = 'SilentlyContinue'
          $vmName = "{{ vm_name | replace('"', '`"') }}"
          $snapshotName = "{{ snapshot_name | replace('"', '`"') }}"
          Restore-VMSnapshot -VMName $vmName -Name $snapshotName -Confirm:$false -ErrorAction Stop *> $null
          Write-Host "SUCCESS"
          exit 0
        } catch {
          Write-Host "FAILED: $($_.Exception.Message)"
          exit 1
        }
      register: restore_result
      failed_when: false
      
    - name: Display result
      debug:
        msg: "{{ restore_result.stdout_lines }}"
        
    - name: Check if restore succeeded
      fail:
        msg: "Restore operation failed"
      when: restore_result.rc != 0

