---
- name: Restore Hyper-V VM from Snapshot
  hosts: all
  gather_facts: no
  vars:
    skip_verify: true 

  tasks:
    - name: Validate required variables
      fail:
        msg: "Both vm_name and snapshot_name are required"
      when: >
        (vm_name is not defined or vm_name == "" or vm_name | trim == "") or
        (snapshot_name is not defined or snapshot_name == "" or snapshot_name | trim == "")

    - name: Restore VM from snapshot (this may take several minutes)
      win_command: >
        powershell.exe -NoLogo -NoProfile -Command
        "$success = @{ status = 'SUCCESS' } | ConvertTo-Json -Compress;
        $fail    = @{ status = 'FAILED' }  | ConvertTo-Json -Compress;
        Restore-VMSnapshot -VMName '{{ vm_name }}' -Name '{{ snapshot_name }}' -Confirm:$false | Out-Null;
        if ($?) { Write-Output $success } else { Write-Output $fail; exit 1 }"
      register: restore_result
      changed_when: ((restore_result.stdout | default('{}')) | from_json).status == 'SUCCESS'

    - name: debug
      ansible.
      register: restore_result

    - name: Check restore status
      fail:
        msg: "Restore operation failed"
      when:
        - not (skip_verify | bool)
        - restore_result.rc is defined
        - restore_result.rc != 0

    - name: Display result
      debug:
        msg: "VM '{{ vm_name }}' has been restored from snapshot '{{ snapshot_name }}' successfully"
