---
- name: Send Email via SMTP
  hosts: localhost
  gather_facts: false
  tags:
    - send-email 
  
  vars:
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    smtp_username: "{{ email_username | default('ittipatjitrada@gmail.com') }}"
    smtp_password: "{{ email_password | default('lsex hcfu pmaf stre') }}"
    email_from: "{{ smtp_username }}"
    email_to: "{{ recipient_email | default(smtp_username) }}"
    email_subject: "{{ subject | default('Notification from Ansible AWX') }}"
    email_body: "{{ body | default('This is an automated email sent from Ansible AWX.') }}"
    email_cc: "{{ cc_recipients | default([]) }}"
    email_bcc: "{{ bcc_recipients | default([]) }}"
    
  tasks:
    - name: Send email notification using Python
      ansible.builtin.shell: |
        python3 << 'EOF'
        import smtplib
        from email.mime.text import MIMEText
        from email.mime.multipart import MIMEMultipart
        
        # Email configuration
        smtp_host = "{{ smtp_host }}"
        smtp_port = {{ smtp_port }}
        username = "{{ smtp_username }}"
        password = "{{ smtp_password }}"
        from_addr = "{{ email_from }}"
        to_addr = "{{ email_to }}"
        subject = "{{ email_subject }}"
        body = """{{ email_body }}"""
        
        # Create message
        msg = MIMEMultipart()
        msg['From'] = from_addr
        msg['To'] = to_addr
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'plain'))
        
        # Send email
        try:
            server = smtplib.SMTP(smtp_host, smtp_port)
            server.starttls()
            server.login(username, password)
            server.send_message(msg)
            server.quit()
            print("Email sent successfully!")
        except Exception as e:
            print(f"Failed to send email: {str(e)}")
            exit(1)
        EOF
      delegate_to: localhost
      no_log: true
      register: email_result
      
    - name: Display email result
      ansible.builtin.debug:
        msg: "{{ email_result.stdout_lines }}"
