---
- name: Create Hyper-V VM Snapshots
  hosts: all
  gather_facts: yes
  # vm_names can be set in AWX as an extra variable or survey
  # Examples:
  #   - String from survey: vm_names: "vm1,vm2" or vm_names: "vm1"
  #   - List: vm_names: ["vm1", "vm2"]
  #   - Empty/not set: vm_names: [] or leave unset (will snapshot all VMs)
    
  tasks:
    - name: Get formatted date and time
      set_fact:
        snapshot_date: "{{ ansible_date_time.date.split('-') | reverse | join('/') }}"
        snapshot_time: "{{ ansible_date_time.time }}"
      
    - name: Normalize vm_names to a list (handle string from AWX survey)
      set_fact:
        vm_names_normalized: >-
          {%- if vm_names is not defined or vm_names == '' -%}
            []
          {%- elif vm_names is string -%}
            {%- if ',' in vm_names -%}
              {{ vm_names.split(',') | map('trim') | list | select('length') | list }}
            {%- else -%}
              {{ [vm_names | trim] }}
            {%- endif -%}
          {%- elif vm_names is iterable and vm_names is not string -%}
            {{ vm_names | list }}
          {%- else -%}
            []
          {%- endif -%}
      
    - name: Get all VMs if no specific VMs specified
      win_shell: |
        $ErrorActionPreference = 'Stop'
        try {
            $vms = @(Get-VM | Select-Object -ExpandProperty Name)
            if ($vms.Count -eq 0) {
                Write-Output '[]'
            } elseif ($vms.Count -eq 1) {
                Write-Output "[`"$($vms[0])`"]"
            } else {
                $vms | ConvertTo-Json -Compress
            }
        } catch {
            Write-Output '[]'
        }
      register: all_vms
      when: vm_names_normalized | length == 0
      changed_when: false
      
    - name: Set VM list from all VMs
      set_fact:
        target_vms: "{{ all_vms.stdout | default('[]') | trim | from_json }}"
      when: vm_names_normalized | length == 0
      
    - name: Set VM list from provided names
      set_fact:
        target_vms: "{{ vm_names_normalized }}"
      when: vm_names_normalized | length > 0
      
    - name: Display VMs to be snapshotted
      debug:
        msg: "Creating snapshots for VMs: {{ target_vms }}"
        
    - name: Create Hyper-V checkpoint/snapshot
      win_shell: |
        try {
          $ProgressPreference = 'SilentlyContinue'
          $vmName = "{{ item | replace('"', '`"') }}"
          $snapshotName = "$vmName - ({{ snapshot_date }} - {{ snapshot_time }})"
          Checkpoint-VM -Name $vmName -SnapshotName $snapshotName -ErrorAction Stop *> $null
          Write-Host "SUCCESS: $vmName"
          exit 0
        } catch {
          Write-Host "FAILED: $vmName - $($_.Exception.Message)"
          exit 1
        }
      loop: "{{ target_vms }}"
      register: snapshot_results
      failed_when: false
      
    - name: Display snapshot results
      debug:
        msg: "{{ snapshot_results.results | map(attribute='stdout') | list }}"
        
    - name: Check for any failures
      fail:
        msg: "One or more snapshots failed: {{ item.stdout }}"
      when: item.rc != 0
      loop: "{{ snapshot_results.results }}"

