---
- name: Test Connection to Linux Hosts
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: Test SSH connectivity
      ping:
      register: ping_result
      
    - name: Display connection success
      debug:
        msg: "Successfully connected to {{ inventory_hostname }}"
      when: ping_result is succeeded
      
    - name: Get system information
      shell: |
        os_name=$(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '"')
        echo "OS:${os_name}"
        echo "Kernel:$(uname -r)"
        echo "Hostname:$(hostname)"
        echo "Uptime:$(uptime -p 2>/dev/null || uptime | awk '{print $3,$4}' | sed 's/,//')"
        echo "IPAddress:$(hostname -I | awk '{print $1}')"
      register: system_info
      changed_when: false
      
    - name: Display system information
      debug:
        msg: "{{ system_info.stdout_lines }}"
      
    - name: Get CPU and memory information
      shell: |
        echo "CPU:$(nproc) cores"
        echo "Memory:$(free -h | grep Mem | awk '{print $2 " total, " $3 " used, " $7 " available"}')"
        echo "Disk:$(df -h / | tail -1 | awk '{print $2 " total, " $3 " used, " $4 " available (" $5 " used)"}')"
      register: resource_info
      changed_when: false
      
    - name: Display resource information
      debug:
        msg: "{{ resource_info.stdout_lines }}"
      
    - name: Check if Docker is installed
      shell: |
        if command -v docker &> /dev/null; then
            echo "Docker installed: Yes"
            docker --version
            echo "Docker containers: $(docker ps -q | wc -l) running"
        else
            echo "Docker installed: No"
        fi
      register: docker_check
      ignore_errors: yes
      changed_when: false
      
    - name: Display Docker status
      debug:
        msg: "{{ docker_check.stdout_lines }}"
      when: docker_check is succeeded
      
    - name: Check common services status
      shell: |
        services=("sshd" "docker" "nginx" "apache2" "httpd")
        for service in "${services[@]}"; do
            if systemctl list-unit-files | grep -q "^${service}.service"; then
                status=$(systemctl is-active ${service} 2>/dev/null || echo "unknown")
                echo "${service}: ${status}"
            fi
        done
      register: services_check
      ignore_errors: yes
      changed_when: false
      
    - name: Display services status
      debug:
        msg: "{{ services_check.stdout_lines }}"
      when: services_check is succeeded and services_check.stdout != ''
      
    - name: Get network interfaces
      shell: |
        ip -4 addr show | grep -E "^[0-9]+:|inet " | awk '
        /^[0-9]+:/ {iface=$2; gsub(/:/, "", iface); gsub(/@.*/, "", iface)}
        /inet / {print iface ": " $2}
        ' | head -5
      register: network_info
      ignore_errors: yes
      changed_when: false
      
    - name: Display network interfaces
      debug:
        msg: "{{ network_info.stdout_lines }}"
      when: network_info is succeeded and network_info.stdout != ''
      
    - name: Summary
      debug:
        msg:
          - "=========================================="
          - "Host: {{ inventory_hostname }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Hostname: {{ ansible_hostname }}"
          - "IP Address: {{ ansible_default_ipv4.address | default('N/A') }}"
          - "Connection: SUCCESS"
          - "=========================================="
