---
- name: Troubleshoot WinRM Connection
  hosts: all
  gather_facts: no
  vars:
    target_host: "{{ inventory_hostname }}"
    target_port: "{{ ansible_port | default(5985) }}"
    
  tasks:
    - name: Display connection parameters
      debug:
        msg:
          - "Attempting to connect to: {{ target_host }}"
          - "Port: {{ target_port }}"
          - "Transport: {{ ansible_winrm_transport | default('not set') }}"
          - "Scheme: {{ ansible_winrm_scheme | default('http') }}"
          - "User: {{ ansible_user | default('not set') }}"
          - "Connection: {{ ansible_connection | default('winrm') }}"
          
    - name: Test basic network connectivity (from AWX runner)
      raw: |
        python3 -c "
        import socket
        import sys
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(5)
            result = sock.connect_ex(('{{ target_host }}', {{ target_port }}))
            sock.close()
            if result == 0:
                print('SUCCESS: Port {{ target_port }} is reachable')
                sys.exit(0)
            else:
                print('FAILED: Port {{ target_port }} is not reachable (error code: {})'.format(result))
                sys.exit(1)
        except Exception as e:
            print('ERROR: {}'.format(str(e)))
            sys.exit(1)
        "
      register: port_check
      ignore_errors: yes
      changed: false
      
    - name: Display port check result
      debug:
        msg: "{{ port_check.stdout_lines }}"
        
    - name: Test WinRM endpoint (HTTP GET)
      raw: |
        python3 -c "
        import urllib.request
        import urllib.error
        import sys
        try:
            url = 'http://{{ target_host }}:{{ target_port }}/wsman'
            req = urllib.request.Request(url)
            req.add_header('Content-Type', 'application/soap+xml')
            try:
                with urllib.request.urlopen(req, timeout=5) as response:
                    print('SUCCESS: WinRM endpoint is responding')
                    print('Status: {}'.format(response.status))
                    sys.exit(0)
            except urllib.error.HTTPError as e:
                print('RESPONSE: WinRM endpoint responded with HTTP {}'.format(e.code))
                sys.exit(0)
            except urllib.error.URLError as e:
                print('ERROR: WinRM endpoint not reachable - {}'.format(str(e.reason)))
                sys.exit(1)
        except Exception as e:
            print('ERROR: {}'.format(str(e)))
            sys.exit(1)
        "
      register: winrm_check
      ignore_errors: yes
      changed: false
      
    - name: Display WinRM check result
      debug:
        msg: "{{ winrm_check.stdout_lines }}"
        
    - name: Try alternative ports
      raw: |
        python3 -c "
        import socket
        ports = [5985, 5986]
        for port in ports:
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(3)
                result = sock.connect_ex(('{{ target_host }}', port))
                sock.close()
                if result == 0:
                    print('Port {}: OPEN'.format(port))
                else:
                    print('Port {}: CLOSED'.format(port))
            except:
                print('Port {}: ERROR'.format(port))
        "
      register: port_scan
      ignore_errors: yes
      changed: false
      
    - name: Display port scan results
      debug:
        msg: "{{ port_scan.stdout_lines }}"
        
    - name: Summary and recommendations
      debug:
        msg:
          - "=========================================="
          - "TROUBLESHOOTING SUMMARY"
          - "=========================================="
          - "Host: {{ target_host }}"
          - "Port: {{ target_port }}"
          - ""
          - "If port is not reachable:"
          - "  1. Check firewall on Windows host"
          - "  2. Verify WinRM service is running: Get-Service WinRM"
          - "  3. Check network connectivity from AWX to host"
          - "  4. Verify AWX runner can reach the host network"
          - ""
          - "If WinRM endpoint doesn't respond:"
          - "  1. Run setup-windows.ps1 on the Windows host"
          - "  2. Check WinRM listener: Get-WSManInstance winrm/config/listener"
          - "  3. Try HTTPS port 5986 instead"
          - ""
          - "If using AWX inventory:"
          - "  1. Ensure host is added to inventory"
          - "  2. Verify credentials are configured"
          - "  3. Check host variables match connection settings"
          - "=========================================="

